name: CI/CD Pipeline for Streamlit App

on:
  push:
    branches:
      - main  # Run the pipeline on pushes to the main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11.5  # Match your Python version

        # Step 3: Create and activate a virtual environment
    - name: Create and Activate Virtual Environment
      run: |
        python -m venv .venv  # Create a virtual environment
        source .venv/bin/activate  # Activate the virtual environment

    # Install dependencies
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    # Run tests (Optional: Add tests if you have them)
    - name: Run Tests
      run: |
        echo "No tests defined. Add your test suite here."

